export const productList = [
  {
    id: '1',
    title: 'Bridal Dress',
    image: require('../../assets/image1.jpg'),
    price: 1000,
    rating: 4.9,
    category: 'women',
    quantity: 1,
    size: 'M',
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  },
  {
    id: '2',
    title: 'Barat Dress',
    image: require('../../assets/image3.jpg'),
    price: 1000,
    rating: 4.9,
    category: 'women',
    quantity: 1,
    size: 'M',
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
  },
  {
    id: '3',
    title: 'Mayun Dress',
    image: require('../../assets/image4.jpg'),
    price: 1000,
    rating: 4.9,
    category: 'women',
    quantity: 1,
    size: 'M',
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
  },
  {
    id: '4',
    title: 'Behtareen Dress',
    image: require('../../assets/image2.jpg'),
    price: 1000,
    rating: 4.9,
    category: 'women',
    quantity: 1,
    size: 'M',
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
  },
  {
    id: '5',
    title: 'Dress',
    image: require('../../assets/men1.jpg'),
    price: 1000,
    rating: 4.9,
    category: 'men',
    quantity: 1,
    size: 'M',
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  },
  {
    id: '6',
    title: 'Dress',
    image: require('../../assets/men2.jpg'),
    price: 1000,
    rating: 4.9,
    category: 'men',
    quantity: 1,
    size: 'M',
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
  },
  {
    id: '7',
    title: 'Dress',
    image: require('../../assets/men3.jpg'),
    price: 1000,
    rating: 4.9,
    category: 'men',
    quantity: 1,
    size: 'M',
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
  },
  {
    id: '8',
    title: 'Dress',
    image: require('../../assets/men4.jpg'),
    price: 1000,
    rating: 4.9,
    category: 'men',
    quantity: 1,
    size: 'M',
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
  },
  {
    id: '9',
    title: 'Dress',
    image: require('../../assets/kid1.jpg'),
    price: 1000,
    rating: 4.9,
    category: 'kids',
    quantity: 1,
    size: 'M',
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  },
  {
    id: '10',
    title: 'Dress',
    image: require('../../assets/kid2.jpg'),
    price: 1000,
    rating: 4.9,
    category: 'kids',
    quantity: 1,
    size: 'M',
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
  },
  {
    id: '11',
    title: 'Dress',
    image: require('../../assets/kid3.jpg'),
    price: 1000,
    rating: 4.9,
    category: 'kids',
    quantity: 1,
    size: 'M',
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
  },
  {
    id: '12',
    title: 'Dress',
    image: require('../../assets/kid4.jpg'),
    price: 1000,
    rating: 4.9,
    category: 'kids',
    quantity: 1,
    size: 'M',
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
  },
]
